### PR TITLE
add translation process and french translation.

### PR DESCRIPTION
**Pull request by Houston4444**
All is in the title.
I added the translation process and translated the app in french.

When installed the 'locale' dir containing *.qm files is installed in `$(PREFIX)/share/qjackcapture` , where `$(PREFIX)` can be /usr or /usr/local for example.

I used the RaySession/Patchance way for checking lrelease executable (may be lerelease-qt5, lrelease-qt4, or lrelease).

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Many thanks for this! Quite some work went into this, I see. However, I would like to hold back merging this until #5 is merged, as this will add a lot of UI text. It would be great if you could update the PR then.

**Comment by Houston4444** [comment]
Sure. No problem. I'll do that when #5 will be merged.

**Comment by Houston4444** [comment]
Ok, I just updated the translation. I also added the Qt base translation for the file picker and close buttons.

**Comment by SpotlightKid** [comment]
Merged with a few changes of my own via c5ff114 and 24af23c.

Many thanks!

**Comment by Houston4444** [comment]
Cool ! And nice to see your corrections.
Curiosity: what is the interest to put translations in resources.qrc file ?

**Comment by SpotlightKid** [comment]
So that it would be easier to distribute the app as a Python wheel (still need to install the desktop and icon files, though).

**Comment by SpotlightKid** [comment]
BTW, how do I update the *.ts files?

**Comment by Houston4444** [comment]
> So that it would be easier to distribute the app as a Python wheel (still need to install the desktop and icon files, though).

Ok, I see.

> BTW, how do I update the *.ts files?

`pylupdate5 qjackcapture.pro`

I personally use a custom shell script to do that, in order to auto-update the new .ui and .py files containing translations in the .pro file, see https://github.com/Houston4444/Patchance/blob/master/locale/update_pro.sh for example.

**Pull request closed without merging**
