### PR TITLE
Add NSM integration

### LINKED ISSUE #1: add NSM support
I think that a NSM support would be interesting for this tool.
The main idea is that records would go into a folder inside the session.
It could also offer show/hide GUI option, and save settings per session too.

### PR DESCRIPTION
**Pull request by SpotlightKid**
Fixes: #1

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Source archive of the `feat/nsm-support` branch for testing:

[QJackCapture-0.3.0.dev0.tar.gz](https://github.com/SpotlightKid/qjackcapture/files/9956612/QJackCapture-0.3.0.dev0.tar.gz)

**Comment by Houston4444** [comment]
There is a big error in save path. For example in RS, QSettings saves the .ini file in `/home/user/.config/home/user/Ray Sessions/session_name/QJackCapture.qcapture.ini`

I took some time to understand what was wrong ;) And how save could work without any file in the session folder.

**Comment by Houston4444** [comment]
Else, all seems good. JACK client is well named, audio file is saved if we shutoff the program while recording (very nice).

It gives me an idea for a very convenient option (but also quite complex because incompatible with freewheeling): Record at startup. This way, when all is well configured, we just have to start/stop the client to record, no need to display its window first. The problem is that new-session-manager still starts all clients at session load (grrr ;)).

**Comment by SpotlightKid** [comment]
Interesting. Can you change [this line](https://github.com/SpotlightKid/qjackcapture/blob/59fbe47e0a7fbbe17b457d767570caa8f4975315/qjackcapture/app.py#L1207) to

```
log_level = logging.DEBUG
```

and start raysession from a terminal and load and save a project with QJackCapture in it.
What is the filename in the log line that goes ""Saving project settings to '...'.".
And what do the log lines, which start with "nsmOpenCallback:" resp "nsmSaveCallback:" say?

**Comment by Houston4444** [comment]
```
[QJackCapture-qcapture_2]
QJackCapture:DEBUG: Incoming OSC message: OSC Message: /nsm/client/save params: []
QJackCapture:INFO: Telling our client to save as /home/houston/Ray Sessions/chansons/headroom_piano_bis/QJackCapture.qcapture_2
QJackCapture:DEBUG: nsmSaveCallback: '/home/houston/Ray Sessions/chansons/headroom_piano_bis/QJackCapture.qcapture_2', 'headroom_piano_bis', 'QJackCapture.qcapture_2'
QJackCapture:DEBUG: Saving project settings to '/home/houston/Ray Sessions/chansons/headroom_piano_bis/QJackCapture.qcapture_2.ini'.
```
That is globally what I've already done this morning (I used -d argument directly, but this is quite equal).

for more debug, in saveSettings() function I added this:
`sys.stderr.write('sldkff%s\n' % settings.fileName())`

and here is the result:
`sldkff/home/houston/.config/home/houston/Ray Sessions/chansons/headroom_piano_bis/QJackCapture.qcapture_2.ini.conf`

**Comment by Houston4444** [comment]
I've got it. You have to change:
`settings = QSettings(path)`

to :

`settings = QSettings(path, QSettings.IniFormat)`

**Comment by SpotlightKid** [comment]
Aha. I had that in before, but then added `QSettings.setDefaultFormat(QSettings.IniFormat)` in the init method of `QJackCaptureApp`. Apparently that is not enough.

**Comment by SpotlightKid** [comment]
I fixed this in 18f546f. Please re-test (see readme for install instructions using a git checkout).

**Comment by Houston4444** [comment]
Works well !

**Comment by SpotlightKid** [comment]
> Record at startup

This is now tracked at #6. No promises, though.

**Pull request merged**
